from setuptools import find_packages, setup


with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="openmanus",
    version="0.1.0",
    author="mannaandpoem and OpenManus Team",
    author_email="mannaandpoem@gmail.com",
    description="A versatile agent that can solve various tasks using multiple tools",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/FoundationAgents/OpenManus",
    packages=find_packages(),
    install_requires=[
        "pydantic>=2.11.0,<3.0",
        "openai>=2.8.0,<3.0",
        "tenacity~=9.0.0",
        "pyyaml~=6.0.2",
        "loguru~=0.7.3",
        "numpy>=1.26.0",
        "datasets>=3.2,<3.5",
        "html2text~=2024.2.26",
        "gymnasium>=1.0,<1.2",
        "pillow>=10.4,<12.0",
        "browsergym~=0.13.3",
        "uvicorn~=0.34.0",
        "unidiff~=0.7.5",
        "browser-use>=0.4.0,<0.5.0",
        "googlesearch-python~=1.3.0",
        "aiofiles~=24.1.0",
        "structlog>=24.1.0,<25.0.0",
        "boto3~=1.37.18",
        "pydantic_core>=2.46.0,<3.0",
        "colorama~=0.4.6",
        "playwright>=1.52.0,<1.53.0",
        "docker~=7.1.0",
        "baidusearch~=1.0.3",
        "fastapi~=0.115.11",
        "duckduckgo_search~=7.5.3",
        "pytest~=8.3.5",
        "pytest-asyncio~=0.25.3",
        "mcp~=1.5.0",
        "httpx>=0.27.0",
        "tomli>=2.0.0",
        "requests~=2.32.3",
        "beautifulsoup4~=4.13.3",
        "crawl4ai>=0.9.0",
        "huggingface-hub~=0.29.2",
        "setuptools~=75.8.0",
        "tiktoken~=0.9.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.12",
    entry_points={
        "console_scripts": [
            "openmanus=main:main",
        ],
    },
)
